# Dependabot configuration
# https://docs.github.com/en/code-security/dependabot

version: 2
updates:
  # Enable version updates for npm
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 10
    commit-message:
      prefix: "deps"
    
    # Labels for pull requests
    labels:
      - "dependencies"
      - "automerge"
    
    # Ignore major version updates
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]

  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
    commit-message:
      prefix: "ci"
