"""Utils package for RabAI AutoClick.

This package uses lazy loading to avoid importing PyQt5-dependent modules
until they are actually needed. This allows tests to import non-PyQt5
modules without requiring PyQt5 to be installed.
"""

from typing import Any

# Lazy loading map: module_name -> (import_path, attribute_names)
_LAZY_IMPORTS = {
    # Hotkey - PyQt5 dependent
    'HotkeyManager': ('utils.hotkey', 'HotkeyManager'),
    # Logger - no PyQt5
    'Logger': ('utils.logger', 'Logger'),
    'logger': ('utils.logger', 'logger'),
    'AppLogger': ('utils.app_logger', 'AppLogger'),
    'app_logger': ('utils.app_logger', 'app_logger'),
    # Memory - PyQt5 dependent
    'MemoryManager': ('utils.memory', 'MemoryManager'),
    'ImageCache': ('utils.memory', 'ImageCache'),
    'memory_manager': ('utils.memory', 'memory_manager'),
    'image_cache': ('utils.memory', 'image_cache'),
    # Recording - PyQt5 dependent
    'RecordingManager': ('utils.recording', 'RecordingManager'),
    'RecordingEditor': ('utils.recording', 'RecordingEditor'),
    'RecordedAction': ('utils.recording', 'RecordedAction'),
    'PYNPUT_AVAILABLE': ('utils.recording', 'PYNPUT_AVAILABLE'),
    # History - PyQt5 dependent
    'WorkflowHistoryManager': ('utils.history', 'WorkflowHistoryManager'),
    'HistoryDialog': ('utils.history', 'HistoryDialog'),
    'QuickSaveDialog': ('utils.history', 'QuickSaveDialog'),
    # Key Display - PyQt5 dependent
    'KeyDisplayWindow': ('utils.key_display', 'KeyDisplayWindow'),
    'key_display_window': ('utils.key_display', 'key_display_window'),
    # Validation - no PyQt5
    'ValidationError': ('utils.validation', 'ValidationError'),
    'ValidationResult': ('utils.validation', 'ValidationResult'),
    'Severity': ('utils.validation', 'Severity'),
    'validate_workflow_config': ('utils.validation', 'validate_workflow_config'),
    'validate_step': ('utils.validation', 'validate_step'),
    'validate_coordinates': ('utils.validation', 'validate_coordinates'),
    'validate_file_path': ('utils.validation', 'validate_file_path'),
    'validate_action_params': ('utils.validation', 'validate_action_params'),
    'validate_screen_region': ('utils.validation', 'validate_screen_region'),
    'sanitize_string': ('utils.validation', 'sanitize_string'),
    'validate_json_serializable': ('utils.validation', 'validate_json_serializable'),
    # Retry - no PyQt5
    'RetryError': ('utils.retry', 'RetryError'),
    'retry': ('utils.retry', 'retry'),
    'retry_async': ('utils.retry', 'retry_async'),
    'CircuitBreaker': ('utils.retry', 'CircuitBreaker'),
    'CircuitState': ('utils.retry', 'CircuitState'),
    'CircuitBreakerConfig': ('utils.retry', 'CircuitBreakerConfig'),
    'RateLimiter': ('utils.retry', 'RateLimiter'),
    'rate_limit': ('utils.retry', 'rate_limit'),
    # Config - no PyQt5
    'ConfigManager': ('utils.config_manager', 'ConfigManager'),
    'config_manager': ('utils.config_manager', 'config_manager'),
    'AppConfig': ('utils.config_manager', 'AppConfig'),
    'DEFAULT_CONFIG': ('utils.config_manager', 'DEFAULT_CONFIG'),
    # Timer - PyQt5 dependent
    'Timer': ('utils.timer', 'Timer'),
    'timed': ('utils.timer', 'timed'),
    'IntervalTimer': ('utils.timer', 'IntervalTimer'),
    'AsyncIntervalTimer': ('utils.timer', 'AsyncIntervalTimer'),
    'Debouncer': ('utils.timer', 'Debouncer'),
    'Throttler': ('utils.timer', 'Throttler'),
    'PerformanceTimer': ('utils.timer', 'PerformanceTimer'),
    'TimingResult': ('utils.timer', 'TimingResult'),
    # Metrics - no PyQt5
    'Counter': ('utils.metrics', 'Counter'),
    'Gauge': ('utils.metrics', 'Gauge'),
    'Histogram': ('utils.metrics', 'Histogram'),
    'MetricsCollector': ('utils.metrics', 'MetricsCollector'),
    'metrics': ('utils.metrics', 'metrics'),
    # Transform - no PyQt5
    'transform': ('utils.transform', 'transform'),
    'transform_dict': ('utils.transform', 'transform_dict'),
    'filter_map': ('utils.transform', 'filter_map'),
    'flatten': ('utils.transform', 'flatten'),
    'group_by': ('utils.transform', 'group_by'),
    'chunk': ('utils.transform', 'chunk'),
    'pluck': ('utils.transform', 'pluck'),
    'merge': ('utils.transform', 'merge'),
    'pick': ('utils.transform', 'pick'),
    'omit': ('utils.transform', 'omit'),
    'map_values': ('utils.transform', 'map_values'),
    'invert': ('utils.transform', 'invert'),
    'deep_get': ('utils.transform', 'deep_get'),
    'deep_set': ('utils.transform', 'deep_set'),
    'sanitize_string': ('utils.transform', 'sanitize_string'),
    'truncate': ('utils.transform', 'truncate'),
    'normalize_whitespace': ('utils.transform', 'normalize_whitespace'),
    'camel_to_snake': ('utils.transform', 'camel_to_snake'),
    'snake_to_camel': ('utils.transform', 'snake_to_camel'),
    'parse_int': ('utils.transform', 'parse_int'),
    'parse_float': ('utils.transform', 'parse_float'),
    'parse_bool': ('utils.transform', 'parse_bool'),
    'coerce_type': ('utils.transform', 'coerce_type'),
    # File Watcher - no PyQt5
    'FileWatcher': ('utils.file_watcher', 'FileWatcher'),
    'FileEvent': ('utils.file_watcher', 'FileEvent'),
    'FileEventType': ('utils.file_watcher', 'FileEventType'),
    'ConfigWatcher': ('utils.file_watcher', 'ConfigWatcher'),
    'DirectoryWatcher': ('utils.file_watcher', 'DirectoryWatcher'),
    # Math Utils - no PyQt5
    'clamp': ('utils.math_utils', 'clamp'),
    'lerp': ('utils.math_utils', 'lerp'),
    'inverse_lerp': ('utils.math_utils', 'inverse_lerp'),
    'map_range': ('utils.math_utils', 'map_range'),
    'mean': ('utils.math_utils', 'mean'),
    'median': ('utils.math_utils', 'median'),
    'mode': ('utils.math_utils', 'mode'),
    'variance': ('utils.math_utils', 'variance'),
    'standard_deviation': ('utils.math_utils', 'standard_deviation'),
    'percentile': ('utils.math_utils', 'percentile'),
    'min_max_normalize': ('utils.math_utils', 'min_max_normalize'),
    'z_score': ('utils.math_utils', 'z_score'),
    'round_to_decimal': ('utils.math_utils', 'round_to_decimal'),
    'is_close': ('utils.math_utils', 'is_close'),
    'gcd': ('utils.math_utils', 'gcd'),
    'lcm': ('utils.math_utils', 'lcm'),
    'is_prime': ('utils.math_utils', 'is_prime'),
    'fibonacci': ('utils.math_utils', 'fibonacci'),
    'factorial': ('utils.math_utils', 'factorial'),
    'combinations': ('utils.math_utils', 'combinations'),
    'permutations': ('utils.math_utils', 'permutations'),
    'format_number': ('utils.math_utils', 'format_number'),
    'format_bytes': ('utils.math_utils', 'format_bytes'),
    'format_duration': ('utils.math_utils', 'format_duration'),
    'distance_2d': ('utils.math_utils', 'distance_2d'),
    'distance_3d': ('utils.math_utils', 'distance_3d'),
    'manhattan_distance': ('utils.math_utils', 'manhattan_distance'),
    'chebyshev_distance': ('utils.math_utils', 'chebyshev_distance'),
    # Collection Utils - no PyQt5
    'unique': ('utils.collection_utils', 'unique'),
    'unique_by': ('utils.collection_utils', 'unique_by'),
    'partition': ('utils.collection_utils', 'partition'),
    'first': ('utils.collection_utils', 'first'),
    'last': ('utils.collection_utils', 'last'),
    'sample': ('utils.collection_utils', 'sample'),
    'transpose': ('utils.collection_utils', 'transpose'),
    'zip_with': ('utils.collection_utils', 'zip_with'),
    'batch': ('utils.collection_utils', 'batch'),
    'sliding_window': ('utils.collection_utils', 'sliding_window'),
    'count_by': ('utils.collection_utils', 'count_by'),
    'group_by_to_dict': ('utils.collection_utils', 'group_by_to_dict'),
    'intersection': ('utils.collection_utils', 'intersection'),
    'union': ('utils.collection_utils', 'union'),
    'difference': ('utils.collection_utils', 'difference'),
    'symmetric_difference': ('utils.collection_utils', 'symmetric_difference'),
    'find': ('utils.collection_utils', 'find'),
    'find_index': ('utils.collection_utils', 'find_index'),
    'contains': ('utils.collection_utils', 'contains'),
    'all_match': ('utils.collection_utils', 'all_match'),
    'none_match': ('utils.collection_utils', 'none_match'),
    'sort_by': ('utils.collection_utils', 'sort_by'),
    'chunk_list': ('utils.collection_utils', 'chunk_list'),
    'deduplicate': ('utils.collection_utils', 'deduplicate'),
    # Dict Utils - no PyQt5
    'get_value': ('utils.dict_utils', 'get_value'),
    'set_value': ('utils.dict_utils', 'set_value'),
    'delete_key': ('utils.dict_utils', 'delete_key'),
    'has_key': ('utils.dict_utils', 'has_key'),
    'get_nested': ('utils.dict_utils', 'get_nested'),
    'set_nested': ('utils.dict_utils', 'set_nested'),
    'delete_nested': ('utils.dict_utils', 'delete_nested'),
    'merge_dicts': ('utils.dict_utils', 'merge_dicts'),
    'diff_dicts': ('utils.dict_utils', 'diff_dicts'),
    'filter_dict': ('utils.dict_utils', 'filter_dict'),
    'map_dict': ('utils.dict_utils', 'map_dict'),
    'invert_dict': ('utils.dict_utils', 'invert_dict'),
    'flatten_dict': ('utils.dict_utils', 'flatten_dict'),
    'unflatten_dict': ('utils.dict_utils', 'unflatten_dict'),
    'pick_keys': ('utils.dict_utils', 'pick_keys'),
    'omit_keys': ('utils.dict_utils', 'omit_keys'),
    'deep_get': ('utils.dict_utils', 'deep_get'),
    'deep_set': ('utils.dict_utils', 'deep_set'),
    'deep_delete': ('utils.dict_utils', 'deep_delete'),
    'dict_from_tuples': ('utils.dict_utils', 'dict_from_tuples'),
    'dict_to_tuples': ('utils.dict_utils', 'dict_to_tuples'),
    'update_if_exists': ('utils.dict_utils', 'update_if_exists'),
    'update_if_not_exists': ('utils.dict_utils', 'update_if_not_exists'),
    'get_or_create': ('utils.dict_utils', 'get_or_create'),
    'count_values': ('utils.dict_utils', 'count_values'),
    'count_keys': ('utils.dict_utils', 'count_keys'),
    'is_empty': ('utils.dict_utils', 'is_empty'),
    'clear_dict': ('utils.dict_utils', 'clear_dict'),
    'swap_keys_values': ('utils.dict_utils', 'swap_keys_values'),
    'rename_key': ('utils.dict_utils', 'rename_key'),
    'extract_subdict': ('utils.dict_utils', 'extract_subdict'),
    'group_by': ('utils.dict_utils', 'group_by'),
    # List Utils - no PyQt5
    'first': ('utils.list_utils', 'first'),
    'last': ('utils.list_utils', 'last'),
    'get_at': ('utils.list_utils', 'get_at'),
    'set_at': ('utils.list_utils', 'set_at'),
    'insert_at': ('utils.list_utils', 'insert_at'),
    'delete_at': ('utils.list_utils', 'delete_at'),
    'append': ('utils.list_utils', 'append'),
    'extend': ('utils.list_utils', 'extend'),
    'prepend': ('utils.list_utils', 'prepend'),
    'unique': ('utils.list_utils', 'unique'),
    'unique_by': ('utils.list_utils', 'unique_by'),
    'filter_list': ('utils.list_utils', 'filter_list'),
    'reject_list': ('utils.list_utils', 'reject_list'),
    'map_list': ('utils.list_utils', 'map_list'),
    'flat_map': ('utils.list_utils', 'flat_map'),
    'reduce_list': ('utils.list_utils', 'reduce_list'),
    'find_item': ('utils.list_utils', 'find_item'),
    'find_index': ('utils.list_utils', 'find_index'),
    'contains_item': ('utils.list_utils', 'contains_item'),
    'all_match': ('utils.list_utils', 'all_match'),
    'none_match': ('utils.list_utils', 'none_match'),
    'partition_list': ('utils.list_utils', 'partition_list'),
    'chunk': ('utils.list_utils', 'chunk'),
    'window': ('utils.list_utils', 'window'),
    'flatten': ('utils.list_utils', 'flatten'),
    'sort_by': ('utils.list_utils', 'sort_by'),
    'reverse_list': ('utils.list_utils', 'reverse_list'),
    'shuffle': ('utils.list_utils', 'shuffle'),
    'sample': ('utils.list_utils', 'sample'),
    'take': ('utils.list_utils', 'take'),
    'drop': ('utils.list_utils', 'drop'),
    'take_while': ('utils.list_utils', 'take_while'),
    'drop_while': ('utils.list_utils', 'drop_while'),
    'zip_with_index': ('utils.list_utils', 'zip_with_index'),
    'unzip_pairs': ('utils.list_utils', 'unzip_pairs'),
    'interleave': ('utils.list_utils', 'interleave'),
    'intersperse': ('utils.list_utils', 'intersperse'),
    'count_items': ('utils.list_utils', 'count_items'),
    'sum_list': ('utils.list_utils', 'sum_list'),
    'product_list': ('utils.list_utils', 'product_list'),
    'average_list': ('utils.list_utils', 'average_list'),
    'min_item': ('utils.list_utils', 'min_item'),
    'max_item': ('utils.list_utils', 'max_item'),
    # File Utils - no PyQt5
    'ensure_dir': ('utils.file_utils', 'ensure_dir'),
    'ensure_parent_dir': ('utils.file_utils', 'ensure_parent_dir'),
    'read_text': ('utils.file_utils', 'read_text'),
    'write_text': ('utils.file_utils', 'write_text'),
    'read_bytes': ('utils.file_utils', 'read_bytes'),
    'write_bytes': ('utils.file_utils', 'write_bytes'),
    'read_json': ('utils.file_utils', 'read_json'),
    'write_json': ('utils.file_utils', 'write_json'),
    'copy_file': ('utils.file_utils', 'copy_file'),
    'move_file': ('utils.file_utils', 'move_file'),
    'delete_file': ('utils.file_utils', 'delete_file'),
    'delete_dir': ('utils.file_utils', 'delete_dir'),
    'file_exists': ('utils.file_utils', 'file_exists'),
    'dir_exists': ('utils.file_utils', 'dir_exists'),
    'get_size': ('utils.file_utils', 'get_size'),
    'get_extension': ('utils.file_utils', 'get_extension'),
    'get_name': ('utils.file_utils', 'get_name'),
    'get_basename': ('utils.file_utils', 'get_basename'),
    'list_files': ('utils.file_utils', 'list_files'),
    'list_dirs': ('utils.file_utils', 'list_dirs'),
    'walk_dir': ('utils.file_utils', 'walk_dir'),
    'is_empty_dir': ('utils.file_utils', 'is_empty_dir'),
    'get_relative_path': ('utils.file_utils', 'get_relative_path'),
    'join_paths': ('utils.file_utils', 'join_paths'),
    'normalize_path': ('utils.file_utils', 'normalize_path'),
    'is_absolute': ('utils.file_utils', 'is_absolute'),
    'make_absolute': ('utils.file_utils', 'make_absolute'),
    # Env Utils - no PyQt5
    'get_env': ('utils.env_utils', 'get_env'),
    'set_env': ('utils.env_utils', 'set_env'),
    'unset_env': ('utils.env_utils', 'unset_env'),
    'get_env_int': ('utils.env_utils', 'get_env_int'),
    'get_env_bool': ('utils.env_utils', 'get_env_bool'),
    'get_env_list': ('utils.env_utils', 'get_env_list'),
    'get_all_env': ('utils.env_utils', 'get_all_env'),
    'has_env': ('utils.env_utils', 'has_env'),
    'is_linux': ('utils.env_utils', 'is_linux'),
    'is_macos': ('utils.env_utils', 'is_macos'),
    'is_windows': ('utils.env_utils', 'is_windows'),
    'get_platform': ('utils.env_utils', 'get_platform'),
    'get_os_version': ('utils.env_utils', 'get_os_version'),
    'get_python_version': ('utils.env_utils', 'get_python_version'),
    'get_platform_info': ('utils.env_utils', 'get_platform_info'),
    'get_cpu_count': ('utils.env_utils', 'get_cpu_count'),
    'get_home_dir': ('utils.env_utils', 'get_home_dir'),
    'get_temp_dir': ('utils.env_utils', 'get_temp_dir'),
    'get_current_dir': ('utils.env_utils', 'get_current_dir'),
    'is_64bit': ('utils.env_utils', 'is_64bit'),
    'is_admin': ('utils.env_utils', 'is_admin'),
    'get_hostname': ('utils.env_utils', 'get_hostname'),
    'get_username': ('utils.env_utils', 'get_username'),
    'get_env_with_prefix': ('utils.env_utils', 'get_env_with_prefix'),
    'set_env_from_dict': ('utils.env_utils', 'set_env_from_dict'),
    'load_env_file': ('utils.env_utils', 'load_env_file'),
    # Validation Utils - no PyQt5
    'is_string': ('utils.validation_utils', 'is_string'),
    'is_int': ('utils.validation_utils', 'is_int'),
    'is_float': ('utils.validation_utils', 'is_float'),
    'is_bool': ('utils.validation_utils', 'is_bool'),
    'is_list': ('utils.validation_utils', 'is_list'),
    'is_dict': ('utils.validation_utils', 'is_dict'),
    'is_email': ('utils.validation_utils', 'is_email'),
    'is_url': ('utils.validation_utils', 'is_url'),
    'is_phone': ('utils.validation_utils', 'is_phone'),
    'is_ipv4': ('utils.validation_utils', 'is_ipv4'),
    'is_port': ('utils.validation_utils', 'is_port'),
    'is_path': ('utils.validation_utils', 'is_path'),
    'is_alphanumeric': ('utils.validation_utils', 'is_alphanumeric'),
    'is_alpha': ('utils.validation_utils', 'is_alpha'),
    'is_numeric': ('utils.validation_utils', 'is_numeric'),
    'is_hex_color': ('utils.validation_utils', 'is_hex_color'),
    'is_username': ('utils.validation_utils', 'is_username'),
    'is_password_strong': ('utils.validation_utils', 'is_password_strong'),
    'is_uuid': ('utils.validation_utils', 'is_uuid'),
    'is_credit_card': ('utils.validation_utils', 'is_credit_card'),
    'in_range': ('utils.validation_utils', 'in_range'),
    'min_length': ('utils.validation_utils', 'min_length'),
    'max_length': ('utils.validation_utils', 'max_length'),
    'matches_pattern': ('utils.validation_utils', 'matches_pattern'),
    'is_one_of': ('utils.validation_utils', 'is_one_of'),
    'validate_type': ('utils.validation_utils', 'validate_type'),
    'validate_schema': ('utils.validation_utils', 'validate_schema'),
    'validate_required_keys': ('utils.validation_utils', 'validate_required_keys'),
    # Time Utils - no PyQt5
    'now': ('utils.time_utils', 'now'),
    'utc_now': ('utils.time_utils', 'utc_now'),
    'timestamp': ('utils.time_utils', 'timestamp'),
    'timestamp_ms': ('utils.time_utils', 'timestamp_ms'),
    'from_timestamp': ('utils.time_utils', 'from_timestamp'),
    'from_timestamp_ms': ('utils.time_utils', 'from_timestamp_ms'),
    'to_timestamp': ('utils.time_utils', 'to_timestamp'),
    'format_datetime': ('utils.time_utils', 'format_datetime'),
    'format_date': ('utils.time_utils', 'format_date'),
    'format_time': ('utils.time_utils', 'format_time'),
    'parse_datetime': ('utils.time_utils', 'parse_datetime'),
    'add_days': ('utils.time_utils', 'add_days'),
    'add_hours': ('utils.time_utils', 'add_hours'),
    'add_minutes': ('utils.time_utils', 'add_minutes'),
    'add_seconds': ('utils.time_utils', 'add_seconds'),
    'days_between': ('utils.time_utils', 'days_between'),
    'hours_between': ('utils.time_utils', 'hours_between'),
    'minutes_between': ('utils.time_utils', 'minutes_between'),
    'seconds_between': ('utils.time_utils', 'seconds_between'),
    'is_weekend': ('utils.time_utils', 'is_weekend'),
    'is_weekday': ('utils.time_utils', 'is_weekday'),
    'start_of_day': ('utils.time_utils', 'start_of_day'),
    'end_of_day': ('utils.time_utils', 'end_of_day'),
    'is_same_day': ('utils.time_utils', 'is_same_day'),
    'is_today': ('utils.time_utils', 'is_today'),
    'is_past': ('utils.time_utils', 'is_past'),
    'is_future': ('utils.time_utils', 'is_future'),
    # String Utils - no PyQt5
    'capitalize': ('utils.string_utils', 'capitalize'),
    'title_case': ('utils.string_utils', 'title_case'),
    'snake_to_camel': ('utils.string_utils', 'snake_to_camel'),
    'camel_to_snake': ('utils.string_utils', 'camel_to_snake'),
    'kebab_to_snake': ('utils.string_utils', 'kebab_to_snake'),
    'snake_to_kebab': ('utils.string_utils', 'snake_to_kebab'),
    'strip_whitespace': ('utils.string_utils', 'strip_whitespace'),
    'normalize_whitespace': ('utils.string_utils', 'normalize_whitespace'),
    'truncate': ('utils.string_utils', 'truncate'),
    'remove_prefix': ('utils.string_utils', 'remove_prefix'),
    'remove_suffix': ('utils.string_utils', 'remove_suffix'),
    'is_blank': ('utils.string_utils', 'is_blank'),
    'is_numeric': ('utils.string_utils', 'is_numeric'),
    'is_alpha': ('utils.string_utils', 'is_alpha'),
    'is_alphanumeric': ('utils.string_utils', 'is_alphanumeric'),
    'count_words': ('utils.string_utils', 'count_words'),
    'reverse_words': ('utils.string_utils', 'reverse_words'),
    'reverse_string': ('utils.string_utils', 'reverse_string'),
    'is_palindrome': ('utils.string_utils', 'is_palindrome'),
    'contains': ('utils.string_utils', 'contains'),
    'replace_all': ('utils.string_utils', 'replace_all'),
    'split_lines': ('utils.string_utils', 'split_lines'),
    'join_lines': ('utils.string_utils', 'join_lines'),
    'indent': ('utils.string_utils', 'indent'),
    'unindent': ('utils.string_utils', 'unindent'),
    'remove_special_chars': ('utils.string_utils', 'remove_special_chars'),
    'normalize_unicode': ('utils.string_utils', 'normalize_unicode'),
    'to_ascii': ('utils.string_utils', 'to_ascii'),
    'word_wrap': ('utils.string_utils', 'word_wrap'),
    'extract_numbers': ('utils.string_utils', 'extract_numbers'),
    'extract_words': ('utils.string_utils', 'extract_words'),
    'filter_chars': ('utils.string_utils', 'filter_chars'),
    'map_chars': ('utils.string_utils', 'map_chars'),
    'pad_left': ('utils.string_utils', 'pad_left'),
    'pad_right': ('utils.string_utils', 'pad_right'),
    'center_text': ('utils.string_utils', 'center_text'),
    # Debug Utils - no PyQt5
    'get_type_name': ('utils.debug_utils', 'get_type_name'),
    'get_type_module': ('utils.debug_utils', 'get_type_module'),
    'get_full_type_name': ('utils.debug_utils', 'get_full_type_name'),
    'get_object_size': ('utils.debug_utils', 'get_object_size'),
    'get_memory_address': ('utils.debug_utils', 'get_memory_address'),
    'get_call_stack': ('utils.debug_utils', 'get_call_stack'),
    'get_frame_info': ('utils.debug_utils', 'get_frame_info'),
    'format_dict': ('utils.debug_utils', 'format_dict'),
    'format_list': ('utils.debug_utils', 'format_list'),
    'inspect_object': ('utils.debug_utils', 'inspect_object'),
    'log_call': ('utils.debug_utils', 'log_call'),
    'log_args': ('utils.debug_utils', 'log_args'),
    'trace_calls': ('utils.debug_utils', 'trace_calls'),
    'dump_locals': ('utils.debug_utils', 'dump_locals'),
    'print_memory_stats': ('utils.debug_utils', 'print_memory_stats'),
    'get_reference_count': ('utils.debug_utils', 'get_reference_count'),
    'get_all_attributes': ('utils.debug_utils', 'get_all_attributes'),
    'has_attribute_chain': ('utils.debug_utils', 'has_attribute_chain'),
    'get_attribute_chain': ('utils.debug_utils', 'get_attribute_chain'),
    'is_debug_mode': ('utils.debug_utils', 'is_debug_mode'),
    # Network Utils - no PyQt5
    'is_valid_ipv4': ('utils.network_utils', 'is_valid_ipv4'),
    'is_valid_ipv6': ('utils.network_utils', 'is_valid_ipv6'),
    'is_valid_port': ('utils.network_utils', 'is_valid_port'),
    'parse_url': ('utils.network_utils', 'parse_url'),
    'build_url': ('utils.network_utils', 'build_url'),
    'parse_query_string': ('utils.network_utils', 'parse_query_string'),
    'build_query_string': ('utils.network_utils', 'build_query_string'),
    'url_encode': ('utils.network_utils', 'url_encode'),
    'url_decode': ('utils.network_utils', 'url_decode'),
    'get_hostname': ('utils.network_utils', 'get_hostname'),
    'get_fqdn': ('utils.network_utils', 'get_fqdn'),
    'resolve_hostname': ('utils.network_utils', 'resolve_hostname'),
    'reverse_dns_lookup': ('utils.network_utils', 'reverse_dns_lookup'),
    'is_reachable': ('utils.network_utils', 'is_reachable'),
    'get_local_ip': ('utils.network_utils', 'get_local_ip'),
    'is_private_ip': ('utils.network_utils', 'is_private_ip'),
    'is_loopback_ip': ('utils.network_utils', 'is_loopback_ip'),
    'parse_http_headers': ('utils.network_utils', 'parse_http_headers'),
    'format_http_headers': ('utils.network_utils', 'format_http_headers'),
    'encode_json': ('utils.network_utils', 'encode_json'),
    'decode_json': ('utils.network_utils', 'decode_json'),
    'is_valid_url': ('utils.network_utils', 'is_valid_url'),
    'is_ssl_port': ('utils.network_utils', 'is_ssl_port'),
    'get_content_type': ('utils.network_utils', 'get_content_type'),
    'join_url_parts': ('utils.network_utils', 'join_url_parts'),
    'normalize_url_path': ('utils.network_utils', 'normalize_url_path'),
    'ip_to_int': ('utils.network_utils', 'ip_to_int'),
    'int_to_ip': ('utils.network_utils', 'int_to_ip'),
    'cidr_to_netmask': ('utils.network_utils', 'cidr_to_netmask'),
    'netmask_to_cidr': ('utils.network_utils', 'netmask_to_cidr'),
    # Date Utils - no PyQt5
    'today': ('utils.date_utils', 'today'),
    'yesterday': ('utils.date_utils', 'yesterday'),
    'tomorrow': ('utils.date_utils', 'tomorrow'),
    'parse_date': ('utils.date_utils', 'parse_date'),
    'format_date': ('utils.date_utils', 'format_date'),
    'is_weekend': ('utils.date_utils', 'is_weekend'),
    'is_weekday': ('utils.date_utils', 'is_weekday'),
    'is_same_day': ('utils.date_utils', 'is_same_day'),
    'is_today': ('utils.date_utils', 'is_today'),
    'is_past': ('utils.date_utils', 'is_past'),
    'is_future': ('utils.date_utils', 'is_future'),
    'add_days_to_date': ('utils.date_utils', 'add_days_to_date'),
    'subtract_days_from_date': ('utils.date_utils', 'subtract_days_from_date'),
    'days_between_dates': ('utils.date_utils', 'days_between_dates'),
    'weeks_between_dates': ('utils.date_utils', 'weeks_between_dates'),
    'months_between_dates': ('utils.date_utils', 'months_between_dates'),
    'years_between_dates': ('utils.date_utils', 'years_between_dates'),
    'start_of_week': ('utils.date_utils', 'start_of_week'),
    'end_of_week': ('utils.date_utils', 'end_of_week'),
    'start_of_month': ('utils.date_utils', 'start_of_month'),
    'end_of_month': ('utils.date_utils', 'end_of_month'),
    'start_of_year': ('utils.date_utils', 'start_of_year'),
    'end_of_year': ('utils.date_utils', 'end_of_year'),
    'get_week_number': ('utils.date_utils', 'get_week_number'),
    'get_quarter': ('utils.date_utils', 'get_quarter'),
    'is_leap_year': ('utils.date_utils', 'is_leap_year'),
    'get_days_in_month': ('utils.date_utils', 'get_days_in_month'),
    'date_range': ('utils.date_utils', 'date_range'),
    'get_weekdays': ('utils.date_utils', 'get_weekdays'),
    'get_weekends': ('utils.date_utils', 'get_weekends'),
    'parse_multiple_dates': ('utils.date_utils', 'parse_multiple_dates'),
    'format_date_range': ('utils.date_utils', 'format_date_range'),
    'get_age': ('utils.date_utils', 'get_age'),
    'is_valid_date': ('utils.date_utils', 'is_valid_date'),
    'date_to_tuple': ('utils.date_utils', 'date_to_tuple'),
    'tuple_to_date': ('utils.date_utils', 'tuple_to_date'),
    'date_to_ordinal': ('utils.date_utils', 'date_to_ordinal'),
    'ordinal_to_date': ('utils.date_utils', 'ordinal_to_date'),
    'get_nth_weekday_of_month': ('utils.date_utils', 'get_nth_weekday_of_month'),
    'get_next_weekday': ('utils.date_utils', 'get_next_weekday'),
    # Random Utils - no PyQt5
    'random_int': ('utils.random_utils', 'random_int'),
    'random_float': ('utils.random_utils', 'random_float'),
    'random_bool': ('utils.random_utils', 'random_bool'),
    'random_choice': ('utils.random_utils', 'random_choice'),
    'random_sample': ('utils.random_utils', 'random_sample'),
    'random_shuffle': ('utils.random_utils', 'random_shuffle'),
    'random_string': ('utils.random_utils', 'random_string'),
    'random_alphanumeric': ('utils.random_utils', 'random_alphanumeric'),
    'random_alpha': ('utils.random_utils', 'random_alpha'),
    'random_numeric': ('utils.random_utils', 'random_numeric'),
    'random_uuid': ('utils.random_utils', 'random_uuid'),
    'random_hex': ('utils.random_utils', 'random_hex'),
    'random_bytes': ('utils.random_utils', 'random_bytes'),
    'random_hash': ('utils.random_utils', 'random_hash'),
    'weighted_choice': ('utils.random_utils', 'weighted_choice'),
    'random_date_year': ('utils.random_utils', 'random_date_year'),
    'random_ip_v4': ('utils.random_utils', 'random_ip_v4'),
    'random_port': ('utils.random_utils', 'random_port'),
    'random_bool_string': ('utils.random_utils', 'random_bool_string'),
    'random_from_set': ('utils.random_utils', 'random_from_set'),
    'random_color_rgb': ('utils.random_utils', 'random_color_rgb'),
    'random_color_hex': ('utils.random_utils', 'random_color_hex'),
    'random_email': ('utils.random_utils', 'random_email'),
    'random_url': ('utils.random_utils', 'random_url'),
    'random_phone': ('utils.random_utils', 'random_phone'),
    'random_credit_card': ('utils.random_utils', 'random_credit_card'),
    'random_paragraph': ('utils.random_utils', 'random_paragraph'),
    'random_sentence': ('utils.random_utils', 'random_sentence'),
    'random_name': ('utils.random_utils', 'random_name'),
    'random_coordinates': ('utils.random_utils', 'random_coordinates'),
    'random_password': ('utils.random_utils', 'random_password'),
    'random_token': ('utils.random_utils', 'random_token'),
    'random_json_friendly': ('utils.random_utils', 'random_json_friendly'),
    # Format Utils - no PyQt5
    'format_bytes': ('utils.format_utils', 'format_bytes'),
    'parse_bytes': ('utils.format_utils', 'parse_bytes'),
    'format_duration': ('utils.format_utils', 'format_duration'),
    'format_duration_long': ('utils.format_utils', 'format_duration_long'),
    'format_number': ('utils.format_utils', 'format_number'),
    'parse_number': ('utils.format_utils', 'parse_number'),
    'format_percent': ('utils.format_utils', 'format_percent'),
    'format_ratio': ('utils.format_utils', 'format_ratio'),
    'truncate_string': ('utils.format_utils', 'truncate_string'),
    'pad_string': ('utils.format_utils', 'pad_string'),
    'wrap_text': ('utils.format_utils', 'wrap_text'),
    'indent_text': ('utils.format_utils', 'indent_text'),
    'format_table': ('utils.format_utils', 'format_table'),
    'format_list': ('utils.format_utils', 'format_list'),
    'format_phone': ('utils.format_utils', 'format_phone'),
    'format_credit_card': ('utils.format_utils', 'format_credit_card'),
    'format_ssn': ('utils.format_utils', 'format_ssn'),
    'format_zip_code': ('utils.format_utils', 'format_zip_code'),
    'pluralize': ('utils.format_utils', 'pluralize'),
    'title_case': ('utils.format_utils', 'title_case'),
    'snake_to_camel': ('utils.format_utils', 'snake_to_camel'),
    'camel_to_snake': ('utils.format_utils', 'camel_to_snake'),
    'kebab_to_snake': ('utils.format_utils', 'kebab_to_snake'),
    'snake_to_kebab': ('utils.format_utils', 'snake_to_kebab'),
    'format_boolean': ('utils.format_utils', 'format_boolean'),
    'format_currency': ('utils.format_utils', 'format_currency'),
    'format_temperature': ('utils.format_utils', 'format_temperature'),
    # Event Bus - PyQt5 dependent
    'Event': ('utils.event_bus', 'Event'),
    'EventPriority': ('utils.event_bus', 'EventPriority'),
    'Subscription': ('utils.event_bus', 'Subscription'),
    'EventBus': ('utils.event_bus', 'EventBus'),
    'EventBusManager': ('utils.event_bus', 'EventBusManager'),
    'event_bus': ('utils.event_bus', 'event_bus'),
    'Events': ('utils.event_bus', 'Events'),
}

# Cache for imported modules
_module_cache = {}


def __getattr__(name: str) -> Any:
    """Lazy import attribute on first access."""
    if name not in _LAZY_IMPORTS:
        raise AttributeError(f"module 'utils' has no attribute '{name}'")

    if name in _module_cache:
        return _module_cache[name]

    import_path, attr_name = _LAZY_IMPORTS[name]

    # Import the module
    import importlib
    module = importlib.import_module(import_path)

    # Get the attribute
    attr = getattr(module, attr_name)

    # Cache it
    _module_cache[name] = attr

    return attr


def __dir__():
    """Return list of available attributes for tab completion."""
    return list(_LAZY_IMPORTS.keys())


# For backward compatibility, also provide __all__
__all__ = list(_LAZY_IMPORTS.keys())