"""UI element caching and lookup utilities.

Maintains a cache of UI element references (buttons, text fields, etc.)
indexed by their properties (label, type, position) to avoid expensive
element lookups in repeated automation tasks.

Example:
    >>> from utils.ui_element_cache_utils import UIElement, UIElementCache
    >>> cache = UIElementCache(max_size=200)
    >>> elem = UIElement(label="Submit", element_type="button", rect=(100, 200, 150, 30))
    >>> cache.put(elem)
    >>> found = cache.find_by_label("Submit")
"""
from __future__ import annotations

import time
from collections import OrderedDict
from dataclasses import dataclass, field
from typing import Any, Literal

__all__ = [
    "UIElement",
    "UIElementCache",
]


@dataclass
class UIElement:
    """Represents a UI element with identifying properties.

    Attributes:
        label: Visible text or accessible name of the element.
        element_type: Type of element (button, textfield, checkbox, etc.).
        rect: Bounding rectangle as (x, y, width, height).
        identifier: Unique identifier (autogenerated if not provided).
        role: Accessibility role name.
        enabled: Whether the element is currently enabled.
        visible: Whether the element is currently visible.
        timestamp: When this element was captured.
    """

    label: str
    element_type: str
    rect: tuple[int, int, int, int]
    identifier: str | None = None
    role: str = "unknown"
    enabled: bool = True
    visible: bool = True
    timestamp: float = field(default_factory=time.time)
    extra: dict[str, Any] = field(default_factory=dict)

    def __post_init__(self) -> None:
        if self.identifier is None:
            self.identifier = f"{self.element_type}::{self.label}::{hash(self.rect)}"

    @property
    def x(self) -> int:
        return self.rect[0]

    @property
    def y(self) -> int:
        return self.rect[1]

    @property
    def width(self) -> int:
        return self.rect[2]

    @property
    def height(self) -> int:
        return self.rect[3]

    @property
    def center(self) -> tuple[int, int]:
        """Return the center point of the element."""
        return (
            self.x + self.width // 2,
            self.y + self.height // 2,
        )

    @property
    def age(self) -> float:
        """Return the age of this element in seconds since capture."""
        return time.time() - self.timestamp

    def matches_label(self, label: str, fuzzy: bool = False) -> bool:
        """Check if the element label matches the given string."""
        if not fuzzy:
            return self.label.lower() == label.lower()
        # Simple fuzzy: substring or edit distance
        return label.lower() in self.label.lower() or self.label.lower() in label.lower()

    def to_dict(self) -> dict:
        """Return a serializable dictionary representation."""
        return {
            "label": self.label,
            "element_type": self.element_type,
            "rect": self.rect,
            "identifier": self.identifier,
            "role": self.role,
            "enabled": self.enabled,
            "visible": self.visible,
            "timestamp": self.timestamp,
            "extra": self.extra,
        }


class UIElementCache:
    """Cache for UI elements with LRU eviction and lookup methods.

    Elements are indexed by identifier, label, type, and position
    for fast retrieval in repeated automation scenarios.

    Example:
        >>> cache = UIElementCache(max_size=100)
        >>> cache.put(element)
        >>> results = cache.find_by_type("button")
        >>> cache.invalidate_stale(max_age=60.0)
    """

    def __init__(self, max_size: int = 200) -> None:
        self._cache: OrderedDict[str, UIElement] = OrderedDict()
        self._max_size = max_size
        self._hits = 0
        self._misses = 0

    def put(self, element: UIElement) -> None:
        """Add an element to the cache.

        Args:
            element: The UIElement to cache.
        """
        if not element.identifier:
            return
        if element.identifier in self._cache:
            self._cache.move_to_end(element.identifier)
        else:
            if len(self._cache) >= self._max_size:
                self._cache.popitem(last=False)
        self._cache[element.identifier] = element

    def get(self, identifier: str) -> UIElement | None:
        """Retrieve an element by its identifier.

        Args:
            identifier: The element's unique identifier.

        Returns:
            The UIElement if found, else None.
        """
        elem = self._cache.get(identifier)
        if elem:
            self._hits += 1
            self._cache.move_to_end(identifier)
            return elem
        self._misses += 1
        return None

    def find_by_label(
        self,
        label: str,
        fuzzy: bool = False,
    ) -> list[UIElement]:
        """Find all elements matching the given label.

        Args:
            label: Label text to search for.
            fuzzy: Use fuzzy matching if True.

        Returns:
            List of matching UIElement objects.
        """
        results = []
        for elem in self._cache.values():
            if elem.matches_label(label, fuzzy=fuzzy):
                results.append(elem)
        return results

    def find_by_type(
        self,
        element_type: str,
    ) -> list[UIElement]:
        """Find all elements of the given type.

        Args:
            element_type: Type string (e.g., 'button', 'textfield').

        Returns:
            List of matching UIElement objects.
        """
        return [
            elem for elem in self._cache.values()
            if elem.element_type.lower() == element_type.lower()
        ]

    def find_in_region(
        self,
        x: int,
        y: int,
        width: int,
        height: int,
    ) -> list[UIElement]:
        """Find all elements that fall within or overlap a region.

        Args:
            x: Left edge of the region.
            y: Top edge of the region.
            width: Width of the region.
            height: Height of the region.

        Returns:
            List of UIElement objects in the region.
        """
        results = []
        x2, y2 = x + width, y + height
        for elem in self._cache.values():
            ex, ey, ew, eh = elem.rect
            ex2, ey2 = ex + ew, ey + eh
            if ex < x2 and ex2 > x and ey < y2 and ey2 > y:
                results.append(elem)
        return results

    def invalidate_stale(self, max_age: float) -> int:
        """Remove elements older than max_age seconds.

        Args:
            max_age: Maximum age in seconds.

        Returns:
            Number of elements removed.
        """
        now = time.time()
        stale = [
            ident for ident, elem in self._cache.items()
            if (now - elem.timestamp) > max_age
        ]
        for ident in stale:
            self._cache.pop(ident, None)
        return len(stale)

    def clear(self) -> None:
        """Clear all cached elements."""
        self._cache.clear()
        self._hits = 0
        self._misses = 0

    def stats(self) -> dict[str, Any]:
        """Return cache statistics."""
        total = self._hits + self._misses
        return {
            "size": len(self._cache),
            "max_size": self._max_size,
            "hits": self._hits,
            "misses": self._misses,
            "hit_rate": self._hits / total if total > 0 else 0.0,
        }
