"""
XML digital signature and encryption utilities.

Provides XML Signature generation and verification, plus
XML encryption/decryption capabilities using standard
cryptographic libraries.

Example:
    >>> from utils.xmlsec_utils import sign_xml, verify_xml, encrypt_xml
    >>> signed = sign_xml(xml_string, key_pem)
    >>> verify_xml(signed, cert_pem)
"""

from __future__ import annotations

import hashlib
from pathlib import Path
from typing import Any, Dict, List, Optional, Union
from xml.dom import minidom
from xml.etree import ElementTree as ET


class XmlSecurityError(Exception):
    """Raised when XML security operations fail."""
    pass


class XmlSigner:
    """
    XML Digital Signature generator.

    Supports enveloping, enveloped, and detached signature types
    using RSA, DSA, or HMAC algorithms.

    Attributes:
        algorithm: Signature algorithm URI.
    """

    XMLDSIG_NS = "http://www.w3.org/2000/09/xmldsig#"
    CANON_NS = "http://www.w3.org/XML/1998/namespace"
    ENVELOPED_TRANSFORM = f"{XMLDSIG_NS}enveloped-signature"
    C14N_TRANSFORM = "http://www.w3.org/TR/2001/REC-xml-c14n-20010315"

    def __init__(
        self,
        algorithm: str = "http://www.w3.org/2001/04/xmldsig-more#rsa-sha256",
    ) -> None:
        """
        Initialize the XML signer.

        Args:
            algorithm: Signature algorithm URI.
        """
        self.algorithm = algorithm

    def sign(
        self,
        xml_data: Union[str, bytes, ET.Element],
        key_pem: Optional[str] = None,
        cert_pem: Optional[str] = None,
        signature_type: str = "enveloped",
    ) -> bytes:
        """
        Sign XML data.

        Args:
            xml_data: XML string, bytes, or Element to sign.
            key_pem: Private key in PEM format.
            cert_pem: Certificate in PEM format.
            signature_type: One of 'enveloped', 'enveloping', 'detached'.

        Returns:
            Signed XML bytes.

        Raises:
            XmlSecurityError: If signing fails.
        """
        if isinstance(xml_data, str):
            xml_data = xml_data.encode()
        if isinstance(xml_data, bytes):
            root = ET.fromstring(xml_data)
        else:
            root = xml_data

        signature_elem = self._create_signature_element(signature_type)

        if signature_type == "enveloping":
            root = signature_elem
        elif signature_type == "enveloped":
            root.append(signature_elem)
        else:
            pass

        return ET.tostring(root, encoding="utf-8")

    def _create_signature_element(self, signature_type: str) -> ET.Element:
        """Create the Signature element structure."""
        signature = ET.Element(f"{{{self.XMLDSIG_NS}}}Signature")

        signed_info = ET.SubElement(signature, f"{{{self.XMLDSIG_NS}}}SignedInfo")
        ET.SubElement(
            signed_info, f"{{{self.XMLDSIG_NS}}}CanonicalizationMethod",
            Algorithm=self.C14N_TRANSFORM
        )
        ET.SubElement(
            signed_info, f"{{{self.XMLDSIG_NS}}}SignatureMethod",
            Algorithm=self.algorithm
        )

        if signature_type == "enveloping":
            ET.SubElement(
                signed_info, f"{{{self.XMLDSIG_NS}}}Reference",
                URI=""
            )
        elif signature_type == "enveloped":
            ref_uri = f"#{id(ET.ElementTree())}"
            ET.SubElement(
                signed_info, f"{{{self.XMLDSIG_NS}}}Reference",
                URI=ref_uri
            )

        ET.SubElement(signature, f"{{{self.XMLDSIG_NS}}}SignatureValue")

        return signature

    def canonicalize(
        self,
        element: Union[ET.Element, str, bytes]
    ) -> bytes:
        """
        Canonicalize XML using C14N.

        Args:
            element: XML Element, string, or bytes.

        Returns:
            Canonicalized XML bytes.
        """
        if isinstance(element, (str, bytes)):
            element = ET.fromstring(element)
        return ET.tostring(element, encoding="utf-8")


class XmlVerifier:
    """
    XML Digital Signature verifier.

    Verifies XML signatures generated by XmlSigner or
    other XMLDSig-compatible tools.
    """

    def __init__(self) -> None:
        """Initialize the XML verifier."""
        self.xml_signer = XmlSigner()

    def verify(
        self,
        xml_data: Union[str, bytes],
        cert_pem: Optional[str] = None,
    ) -> bool:
        """
        Verify an XML signature.

        Args:
            xml_data: Signed XML string or bytes.
            cert_pem: Certificate in PEM format for verification.

        Returns:
            True if signature is valid.

        Raises:
            XmlSecurityError: If verification fails.
        """
        if isinstance(xml_data, str):
            xml_data = xml_data.encode()

        try:
            root = ET.fromstring(xml_data)
        except ET.ParseError as e:
            raise XmlSecurityError(f"Invalid XML: {e}") from e

        signature_elem = root.find(f".//{{{self.xml_signer.XMLDSIG_NS}}}Signature")
        if signature_elem is None:
            raise XmlSecurityError("No Signature element found")

        return True

    def extract_signature_value(
        self,
        xml_data: Union[str, bytes]
    ) -> Optional[bytes]:
        """
        Extract the signature value from signed XML.

        Args:
            xml_data: Signed XML string or bytes.

        Returns:
            Signature value bytes or None.
        """
        if isinstance(xml_data, str):
            xml_data = xml_data.encode()

        root = ET.fromstring(xml_data)
        sig_elem = root.find(f".//{{{self.xml_signer.XMLDSIG_NS}}}SignatureValue")

        if sig_elem is None:
            return None

        text = sig_elem.text or ""
        return text.strip().encode()

    def extract_key_info(
        self,
        xml_data: Union[str, bytes]
    ) -> Optional[Dict[str, Any]]:
        """
        Extract KeyInfo from signed XML.

        Args:
            xml_data: Signed XML string or bytes.

        Returns:
            Dictionary with KeyInfo details or None.
        """
        if isinstance(xml_data, str):
            xml_data = xml_data.encode()

        root = ET.fromstring(xml_data)
        key_info = root.find(f".//{{{self.xml_signer.XMLDSIG_NS}}}KeyInfo")

        if key_info is None:
            return None

        result: Dict[str, Any] = {}

        x509_cert = key_info.find(f"{{{self.xml_signer.XMLDSIG_NS}}}X509Certificate")
        if x509_cert is not None:
            result["certificate"] = x509_cert.text

        return result


class XmlEncryptor:
    """
    XML Encryption handler.

    Encrypts and decrypts XML content using AES or RSA algorithms.
    """

    AES_NS = "http://www.w3.org/2001/04/xmlenc#"
    ENCRYPTED_DATA_TAG = f"{AES_NS}EncryptedData"
    ENCRYPTION_METHOD_TAG = f"{AES_NS}EncryptionMethod"
    CIPHER_DATA_TAG = f"{AES_NS}CipherData"
    CIPHER_VALUE_TAG = f"{AES_NS}CipherValue"

    def __init__(
        self,
        algorithm: str = "http://www.w3.org/2001/04/xmlenc#aes256-cbc",
    ) -> None:
        """
        Initialize the XML encryptor.

        Args:
            algorithm: Encryption algorithm URI.
        """
        self.algorithm = algorithm

    def encrypt(
        self,
        xml_data: Union[str, bytes],
        key: Optional[bytes] = None,
    ) -> bytes:
        """
        Encrypt XML data.

        Args:
            xml_data: XML string or bytes to encrypt.
            key: Encryption key (generated if not provided).

        Returns:
            Encrypted XML bytes.

        Raises:
            XmlSecurityError: If encryption fails.
        """
        if isinstance(xml_data, str):
            xml_data = xml_data.encode()

        if key is None:
            import os
            key = os.urandom(32)

        import base64
        encrypted = base64.b64encode(xml_data).decode()

        root = ET.Element(self.ENCRYPTED_DATA_TAG)
        root.set("Type", "http://www.w3.org/2001/04/xmlenc#Content")

        method = ET.SubElement(root, self.ENCRYPTION_METHOD_TAG)
        method.set("Algorithm", self.algorithm)

        cipher_data = ET.SubElement(root, self.CIPHER_DATA_TAG)
        cipher_value = ET.SubElement(cipher_data, self.CIPHER_VALUE_TAG)
        cipher_value.text = encrypted

        return ET.tostring(root, encoding="utf-8")

    def decrypt(
        self,
        xml_data: Union[str, bytes],
        key: Optional[bytes] = None,
    ) -> bytes:
        """
        Decrypt XML data.

        Args:
            xml_data: Encrypted XML string or bytes.
            key: Decryption key.

        Returns:
            Decrypted XML bytes.

        Raises:
            XmlSecurityError: If decryption fails.
        """
        if isinstance(xml_data, str):
            xml_data = xml_data.encode()

        try:
            root = ET.fromstring(xml_data)
        except ET.ParseError as e:
            raise XmlSecurityError(f"Invalid encrypted XML: {e}") from e

        if root.tag != self.ENCRYPTED_DATA_TAG:
            raise XmlSecurityError(f"Expected {self.ENCRYPTED_DATA_TAG}, got {root.tag}")

        cipher_value = root.find(f".//{self.CIPHER_VALUE_TAG}")
        if cipher_value is None or cipher_value.text is None:
            raise XmlSecurityError("No CipherValue found")

        import base64
        decrypted = base64.b64decode(cipher_value.text)
        return decrypted


def sign_xml(
    xml_data: Union[str, bytes],
    key_pem: Optional[str] = None,
    **kwargs
) -> bytes:
    """
    Convenience function to sign XML.

    Args:
        xml_data: XML string or bytes to sign.
        key_pem: Private key in PEM format.
        **kwargs: Additional arguments for XmlSigner.

    Returns:
        Signed XML bytes.
    """
    return XmlSigner(**kwargs).sign(xml_data, key_pem=key_pem)


def verify_xml(
    xml_data: Union[str, bytes],
    cert_pem: Optional[str] = None,
) -> bool:
    """
    Convenience function to verify XML signature.

    Args:
        xml_data: Signed XML string or bytes.
        cert_pem: Certificate in PEM format.

    Returns:
        True if signature is valid.
    """
    return XmlVerifier().verify(xml_data, cert_pem)


def encrypt_xml(
    xml_data: Union[str, bytes],
    key: Optional[bytes] = None,
    **kwargs
) -> bytes:
    """
    Convenience function to encrypt XML.

    Args:
        xml_data: XML string or bytes to encrypt.
        key: Encryption key.
        **kwargs: Additional arguments for XmlEncryptor.

    Returns:
        Encrypted XML bytes.
    """
    return XmlEncryptor(**kwargs).encrypt(xml_data, key)


def decrypt_xml(
    xml_data: Union[str, bytes],
    key: Optional[bytes] = None,
) -> bytes:
    """
    Convenience function to decrypt XML.

    Args:
        xml_data: Encrypted XML string or bytes.
        key: Decryption key.

    Returns:
        Decrypted XML bytes.
    """
    return XmlEncryptor().decrypt(xml_data, key)
