"""
Automation Monitor Action - Monitors automation workflows and reports metrics.

This module provides monitoring, alerting, and metrics collection
for automation workflows.
"""

from __future__ import annotations

import asyncio
import time
import uuid
from dataclasses import dataclass, field
from typing import Any, Callable
from enum import Enum
from collections import defaultdict
from datetime import datetime


class AlertLevel(Enum):
    """Alert severity levels."""
    INFO = "info"
    WARNING = "warning"
    ERROR = "error"
    CRITICAL = "critical"


@dataclass
class Alert:
    """An alert generated by the monitoring system."""
    alert_id: str
    level: AlertLevel
    message: str
    source: str
    timestamp: float = field(default_factory=time.time)
    metadata: dict[str, Any] = field(default_factory=dict)
    acknowledged: bool = False


@dataclass
class WorkflowMetrics:
    """Metrics for a monitored workflow."""
    workflow_id: str
    execution_count: int = 0
    success_count: int = 0
    failure_count: int = 0
    avg_duration_ms: float = 0.0
    total_duration_ms: float = 0.0
    last_execution: float | None = None
    last_status: str | None = None


@dataclass
class MonitorConfig:
    """Configuration for automation monitoring."""
    collect_metrics: bool = True
    alert_on_failure: bool = True
    alert_on_timeout: bool = True
    metrics_window: float = 3600.0
    max_alerts: int = 100


class AlertHandler:
    """Handler for processing alerts."""
    
    def __init__(self) -> None:
        self._handlers: list[Callable[[Alert], None]] = []
    
    def register(self, handler: Callable[[Alert], None]) -> None:
        """Register an alert handler."""
        self._handlers.append(handler)
    
    async def handle(self, alert: Alert) -> None:
        """Handle an alert through all registered handlers."""
        for handler in self._handlers:
            try:
                result = handler(alert)
                if asyncio.iscoroutine(result):
                    await result
            except Exception:
                pass


class AutomationMonitor:
    """
    Monitors automation workflows and collects metrics.
    
    Example:
        monitor = AutomationMonitor()
        monitor.workflow_started("etl_pipeline")
        # ... run workflow ...
        monitor.workflow_completed("etl_pipeline", success=True)
        metrics = monitor.get_metrics("etl_pipeline")
    """
    
    def __init__(self, config: MonitorConfig | None = None) -> None:
        self.config = config or MonitorConfig()
        self._workflow_metrics: dict[str, WorkflowMetrics] = {}
        self._alerts: list[Alert] = []
        self._alert_handler = AlertHandler()
        self._execution_times: dict[str, list[float]] = defaultdict(list)
    
    def workflow_started(self, workflow_id: str) -> None:
        """Record workflow start."""
        if workflow_id not in self._workflow_metrics:
            self._workflow_metrics[workflow_id] = WorkflowMetrics(workflow_id=workflow_id)
        
        metrics = self._workflow_metrics[workflow_id]
        metrics.execution_count += 1
        metrics.last_execution = time.time()
        metrics.last_status = "running"
    
    def workflow_completed(
        self,
        workflow_id: str,
        success: bool,
        duration_ms: float = 0.0,
        error: str | None = None,
    ) -> None:
        """Record workflow completion."""
        if workflow_id not in self._workflow_metrics:
            self._workflow_metrics[workflow_id] = WorkflowMetrics(workflow_id=workflow_id)
        
        metrics = self._workflow_metrics[workflow_id]
        metrics.last_status = "success" if success else "failed"
        
        if success:
            metrics.success_count += 1
        else:
            metrics.failure_count += 1
            if self.config.alert_on_failure and error:
                self._create_alert(
                    AlertLevel.ERROR,
                    f"Workflow {workflow_id} failed: {error}",
                    workflow_id,
                )
        
        self._execution_times[workflow_id].append(duration_ms)
        self._update_avg_duration(workflow_id, duration_ms)
    
    def _update_avg_duration(self, workflow_id: str, duration_ms: float) -> None:
        """Update average duration metric."""
        metrics = self._workflow_metrics[workflow_id]
        times = self._execution_times[workflow_id]
        
        cutoff = time.time() - self.config.metrics_window
        recent_times = [t for t in times if t >= cutoff]
        
        if recent_times:
            metrics.total_duration_ms = sum(recent_times)
            metrics.avg_duration_ms = metrics.total_duration_ms / len(recent_times)
            self._execution_times[workflow_id] = recent_times
    
    def check_timeout(
        self,
        workflow_id: str,
        timeout_threshold: float,
    ) -> bool:
        """Check if workflow has exceeded timeout threshold."""
        if workflow_id not in self._workflow_metrics:
            return False
        
        metrics = self._workflow_metrics[workflow_id]
        if metrics.last_execution is None:
            return False
        
        elapsed = time.time() - metrics.last_execution
        if elapsed > timeout_threshold and metrics.last_status == "running":
            if self.config.alert_on_timeout:
                self._create_alert(
                    AlertLevel.WARNING,
                    f"Workflow {workflow_id} running for {elapsed:.1f}s (threshold: {timeout_threshold}s)",
                    workflow_id,
                )
            return True
        
        return False
    
    def _create_alert(
        self,
        level: AlertLevel,
        message: str,
        source: str,
        metadata: dict[str, Any] | None = None,
    ) -> Alert:
        """Create and store an alert."""
        if len(self._alerts) >= self.config.max_alerts:
            self._alerts = self._alerts[-self.config.max_alerts // 2:]
        
        alert = Alert(
            alert_id=str(uuid.uuid4()),
            level=level,
            message=message,
            source=source,
            metadata=metadata or {},
        )
        self._alerts.append(alert)
        asyncio.create_task(self._alert_handler.handle(alert))
        return alert
    
    def register_alert_handler(self, handler: Callable[[Alert], None]) -> None:
        """Register a handler for alerts."""
        self._alert_handler.register(handler)
    
    def get_metrics(self, workflow_id: str) -> WorkflowMetrics | None:
        """Get metrics for a workflow."""
        return self._workflow_metrics.get(workflow_id)
    
    def get_all_metrics(self) -> dict[str, WorkflowMetrics]:
        """Get metrics for all workflows."""
        return self._workflow_metrics.copy()
    
    def get_alerts(
        self,
        level: AlertLevel | None = None,
        since: float | None = None,
        unacknowledged_only: bool = False,
    ) -> list[Alert]:
        """Get alerts matching criteria."""
        alerts = self._alerts
        
        if level:
            alerts = [a for a in alerts if a.level == level]
        
        if since:
            alerts = [a for a in alerts if a.timestamp >= since]
        
        if unacknowledged_only:
            alerts = [a for a in alerts if not a.acknowledged]
        
        return alerts
    
    def acknowledge_alert(self, alert_id: str) -> bool:
        """Acknowledge an alert."""
        for alert in self._alerts:
            if alert.alert_id == alert_id:
                alert.acknowledged = True
                return True
        return False


class AutomationMonitorAction:
    """
    Monitor action for automation workflows.
    
    Example:
        monitor = AutomationMonitorAction()
        
        @monitor.workflow()
        async def my_workflow():
            # ... do work ...
            pass
        
        result = await monitor.execute_with_monitoring(my_workflow)
    """
    
    def __init__(self, config: MonitorConfig | None = None) -> None:
        self.monitor = AutomationMonitor(config)
    
    async def execute_with_monitoring(
        self,
        workflow_id: str,
        workflow_func: Callable[[], Any],
        timeout: float | None = None,
    ) -> tuple[Any, WorkflowMetrics]:
        """Execute a workflow with monitoring."""
        self.monitor.workflow_started(workflow_id)
        start_time = time.time()
        
        try:
            result = workflow_func()
            if asyncio.iscoroutine(result):
                if timeout:
                    result = await asyncio.wait_for(result, timeout=timeout)
                else:
                    result = await result
            
            duration_ms = (time.time() - start_time) * 1000
            self.monitor.workflow_completed(workflow_id, success=True, duration_ms=duration_ms)
            return result, self.monitor.get_metrics(workflow_id)
        
        except asyncio.TimeoutError:
            duration_ms = (time.time() - start_time) * 1000
            self.monitor.workflow_completed(
                workflow_id,
                success=False,
                duration_ms=duration_ms,
                error=f"Workflow timed out after {timeout}s",
            )
            raise
        
        except Exception as e:
            duration_ms = (time.time() - start_time) * 1000
            self.monitor.workflow_completed(
                workflow_id,
                success=False,
                duration_ms=duration_ms,
                error=str(e),
            )
            raise
    
    def on_alert(self, handler: Callable[[Alert], None]) -> None:
        """Register an alert handler."""
        self.monitor.register_alert_handler(handler)


# Export public API
__all__ = [
    "AlertLevel",
    "Alert",
    "WorkflowMetrics",
    "MonitorConfig",
    "AlertHandler",
    "AutomationMonitor",
    "AutomationMonitorAction",
]
