"""
Workflow Monitoring Module v1.0
Real-time monitoring for workflow executions, system resources,
performance metrics, and health checks with alerting capabilities.
"""

import time
import threading
import multiprocessing
from typing import Dict, List, Optional, Any, Callable, Tuple
from dataclasses import dataclass, field
from enum import Enum
from datetime import datetime, timedelta
from collections import defaultdict, deque
import logging
import json
import psutil
import queue

# Configure logging
logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)


class MonitoringStatus(Enum):
    """Monitoring status states."""
    HEALTHY = "healthy"
    WARNING = "warning"
    CRITICAL = "critical"
    UNKNOWN = "unknown"
    STOPPED = "stopped"


class MetricType(Enum):
    """Types of metrics that can be monitored."""
    COUNTER = "counter"
    GAUGE = "gauge"
    HISTOGRAM = "histogram"
    TIMER = "timer"
    RATE = "rate"


@dataclass
class MetricValue:
    """A single metric value with timestamp."""
    name: str
    value: float
    timestamp: datetime
    metric_type: MetricType
    tags: Dict[str, str] = field(default_factory=dict)
    unit: str = ""


@dataclass
class MonitoringAlert:
    """Alert generated by the monitoring system."""
    alert_id: str
    metric_name: str
    status: MonitoringStatus
    message: str
    current_value: float
    threshold: float
    timestamp: datetime
    resolved: bool = False
    metadata: Dict[str, Any] = field(default_factory=dict)


@dataclass
class HealthCheckResult:
    """Result of a health check."""
    name: str
    status: MonitoringStatus
    message: str
    duration_ms: float
    timestamp: datetime
    details: Dict[str, Any] = field(default_factory=dict)


class MetricCollector:
    """Collects and stores metrics."""

    def __init__(self, retention_periods: int = 1000):
        self.retention_periods = retention_periods
        self.metrics: Dict[str, deque] = defaultdict(lambda: deque(maxlen=retention_periods))
        self.counters: Dict[str, float] = defaultdict(float)
        self.gauges: Dict[str, float] = {}
        self._lock = threading.Lock()

    def record_metric(self, metric: MetricValue):
        """Record a metric value."""
        with self._lock:
            self.metrics[metric.name].append(metric)

    def increment_counter(self, name: str, value: float = 1.0, tags: Dict[str, str] = None):
        """Increment a counter metric."""
        with self._lock:
            self.counters[name] += value
            metric = MetricValue(
                name=name,
                value=self.counters[name],
                timestamp=datetime.now(),
                metric_type=MetricType.COUNTER,
                tags=tags or {}
            )
            self.metrics[name].append(metric)

    def set_gauge(self, name: str, value: float, tags: Dict[str, str] = None):
        """Set a gauge metric value."""
        with self._lock:
            self.gauges[name] = value
            metric = MetricValue(
                name=name,
                value=value,
                timestamp=datetime.now(),
                metric_type=MetricType.GAUGE,
                tags=tags or {}
            )
            self.metrics[name].append(metric)

    def record_timer(self, name: str, duration_ms: float, tags: Dict[str, str] = None):
        """Record a timer metric."""
        with self._lock:
            metric = MetricValue(
                name=name,
                value=duration_ms,
                timestamp=datetime.now(),
                metric_type=MetricType.TIMER,
                tags=tags or {},
                unit="ms"
            )
            self.metrics[name].append(metric)

    def get_metric_history(self, name: str, duration: timedelta = None) -> List[MetricValue]:
        """Get metric history, optionally filtered by duration."""
        with self._lock:
            if name not in self.metrics:
                return []
            
            metrics = list(self.metrics[name])
            
            if duration:
                cutoff = datetime.now() - duration
                metrics = [m for m in metrics if m.timestamp >= cutoff]
            
            return metrics

    def get_current_value(self, name: str) -> Optional[float]:
        """Get the most recent value for a metric."""
        with self._lock:
            if name in self.metrics and len(self.metrics[name]) > 0:
                return self.metrics[name][-1].value
            if name in self.gauges:
                return self.gauges[name]
            if name in self.counters:
                return self.counters[name]
            return None

    def calculate_rate(self, name: str, window_seconds: float = 60.0) -> float:
        """Calculate the rate of change for a metric over a time window."""
        with self._lock:
            if name not in self.metrics:
                return 0.0
            
            cutoff = datetime.now() - timedelta(seconds=window_seconds)
            recent = [m for m in self.metrics[name] if m.timestamp >= cutoff]
            
            if len(recent) < 2:
                return 0.0
            
            time_span = (recent[-1].timestamp - recent[0].timestamp).total_seconds()
            if time_span == 0:
                return 0.0
            
            value_change = recent[-1].value - recent[0].value
            return value_change / time_span


class AlertRule:
    """Rule for triggering alerts based on metric thresholds."""

    def __init__(
        self,
        name: str,
        metric_name: str,
        threshold: float,
        condition: str = "greater",  # greater, less, equals
        severity: MonitoringStatus = MonitoringStatus.WARNING,
        duration_seconds: float = 0,
        cooldown_seconds: float = 60
    ):
        self.name = name
        self.metric_name = metric_name
        self.threshold = threshold
        self.condition = condition
        self.severity = severity
        self.duration_seconds = duration_seconds
        self.cooldown_seconds = cooldown_seconds
        self.last_triggered: Optional[datetime] = None
        self.triggered_at: Optional[datetime] = None

    def is_triggered(self, current_value: float) -> Tuple[bool, str]:
        """Check if the rule is triggered by the current value."""
        triggered = False
        message = ""

        if self.condition == "greater":
            triggered = current_value > self.threshold
            message = f"{self.metric_name} ({current_value}) > {self.threshold}"
        elif self.condition == "less":
            triggered = current_value < self.threshold
            message = f"{self.metric_name} ({current_value}) < {self.threshold}"
        elif self.condition == "equals":
            triggered = abs(current_value - self.threshold) < 0.001
            message = f"{self.metric_name} ({current_value}) == {self.threshold}"

        if triggered and self.duration_seconds > 0:
            if self.triggered_at is None:
                self.triggered_at = datetime.now()
            else:
                duration = (datetime.now() - self.triggered_at).total_seconds()
                triggered = duration >= self.duration_seconds
                if not triggered:
                    message += f" (duration: {duration:.1f}s / {self.duration_seconds}s)"
        else:
            self.triggered_at = None

        return triggered, message

    def should_send_alert(self) -> bool:
        """Check if an alert should be sent based on cooldown."""
        if self.last_triggered is None:
            return True
        
        cooldown = (datetime.now() - self.last_triggered).total_seconds()
        return cooldown >= self.cooldown_seconds

    def mark_triggered(self):
        """Mark that an alert was triggered."""
        self.last_triggered = datetime.now()
        self.triggered_at = None


class AlertManager:
    """Manages alerts and notification dispatch."""

    def __init__(self):
        self.alerts: Dict[str, MonitoringAlert] = {}
        self.alert_rules: Dict[str, AlertRule] = {}
        self.alert_history: deque = deque(maxlen=1000)
        self._lock = threading.Lock()

    def register_rule(self, rule: AlertRule):
        """Register an alert rule."""
        with self._lock:
            self.alert_rules[rule.name] = rule

    def unregister_rule(self, name: str):
        """Unregister an alert rule."""
        with self._lock:
            if name in self.alert_rules:
                del self.alert_rules[name]

    def check_rules(self, collector: MetricCollector) -> List[MonitoringAlert]:
        """Check all rules against current metric values."""
        new_alerts = []
        
        with self._lock:
            for rule in self.alert_rules.values():
                current_value = collector.get_current_value(rule.metric_name)
                
                if current_value is None:
                    continue
                
                triggered, message = rule.is_triggered(current_value)
                
                if triggered and rule.should_send_alert():
                    alert = MonitoringAlert(
                        alert_id=f"alert_{datetime.now().strftime('%Y%m%d%H%M%S%f')}",
                        metric_name=rule.metric_name,
                        status=rule.severity,
                        message=message,
                        current_value=current_value,
                        threshold=rule.threshold,
                        timestamp=datetime.now()
                    )
                    
                    self.alerts[alert.alert_id] = alert
                    self.alert_history.append(alert)
                    rule.mark_triggered()
                    new_alerts.append(alert)
        
        return new_alerts

    def resolve_alert(self, alert_id: str):
        """Mark an alert as resolved."""
        with self._lock:
            if alert_id in self.alerts:
                self.alerts[alert_id].resolved = True

    def get_active_alerts(self, status: MonitoringStatus = None) -> List[MonitoringAlert]:
        """Get all active (unresolved) alerts."""
        with self._lock:
            alerts = [a for a in self.alerts.values() if not a.resolved]
            if status:
                alerts = [a for a in alerts if a.status == status]
            return alerts

    def get_alert_history(self, limit: int = 100) -> List[MonitoringAlert]:
        """Get alert history."""
        return list(self.alert_history)[-limit:]


class HealthChecker:
    """Performs health checks on system components."""

    def __init__(self):
        self.health_checks: Dict[str, Callable] = {}

    def register_check(self, name: str, check_func: Callable):
        """Register a health check function."""
        self.health_checks[name] = check_func

    def run_check(self, name: str) -> HealthCheckResult:
        """Run a specific health check."""
        if name not in self.health_checks:
            return HealthCheckResult(
                name=name,
                status=MonitoringStatus.UNKNOWN,
                message=f"Health check '{name}' not found",
                duration_ms=0,
                timestamp=datetime.now()
            )
        
        start_time = time.time()
        try:
            result = self.health_checks[name]()
            duration_ms = (time.time() - start_time) * 1000
            
            if isinstance(result, HealthCheckResult):
                return result
            elif isinstance(result, dict):
                return HealthCheckResult(
                    name=name,
                    status=MonitoringStatus(result.get('status', 'healthy')),
                    message=result.get('message', ''),
                    duration_ms=duration_ms,
                    timestamp=datetime.now(),
                    details=result.get('details', {})
                )
            elif result:
                return HealthCheckResult(
                    name=name,
                    status=MonitoringStatus.HEALTHY,
                    message="Check passed",
                    duration_ms=duration_ms,
                    timestamp=datetime.now()
                )
            else:
                return HealthCheckResult(
                    name=name,
                    status=MonitoringStatus.CRITICAL,
                    message="Check failed",
                    duration_ms=duration_ms,
                    timestamp=datetime.now()
                )
        except Exception as e:
            duration_ms = (time.time() - start_time) * 1000
            return HealthCheckResult(
                name=name,
                status=MonitoringStatus.CRITICAL,
                message=f"Check error: {str(e)}",
                duration_ms=duration_ms,
                timestamp=datetime.now()
            )

    def run_all_checks(self) -> Dict[str, HealthCheckResult]:
        """Run all registered health checks."""
        results = {}
        for name in self.health_checks:
            results[name] = self.run_check(name)
        return results

    def get_overall_status(self, results: Dict[str, HealthCheckResult] = None) -> MonitoringStatus:
        """Get overall system status based on health checks."""
        if results is None:
            results = self.run_all_checks()
        
        if not results:
            return MonitoringStatus.UNKNOWN
        
        statuses = [r.status for r in results.values()]
        
        if MonitoringStatus.CRITICAL in statuses:
            return MonitoringStatus.CRITICAL
        elif MonitoringStatus.WARNING in statuses:
            return MonitoringStatus.WARNING
        elif MonitoringStatus.HEALTHY in statuses:
            return MonitoringStatus.HEALTHY
        else:
            return MonitoringStatus.UNKNOWN


class SystemMonitor:
    """Monitors system resources (CPU, memory, disk, network)."""

    def __init__(self, interval: float = 1.0):
        self.interval = interval
        self.process = psutil.Process()
        self._monitoring = False
        self._monitor_thread: Optional[threading.Thread] = None
        self._callbacks: List[Callable] = []

    def get_cpu_usage(self) -> float:
        """Get current CPU usage percentage."""
        try:
            return self.process.cpu_percent(interval=0.1)
        except Exception:
            return 0.0

    def get_memory_usage(self) -> Tuple[float, float]:
        """Get memory usage (RSS in MB, percentage)."""
        try:
            mem_info = self.process.memory_info()
            rss_mb = mem_info.rss / (1024 * 1024)
            mem_percent = self.process.memory_percent()
            return rss_mb, mem_percent
        except Exception:
            return 0.0, 0.0

    def get_disk_usage(self, path: str = "/") -> Tuple[float, float]:
        """Get disk usage (used GB, percentage)."""
        try:
            usage = psutil.disk_usage(path)
            used_gb = usage.used / (1024 * 1024 * 1024)
            return used_gb, usage.percent
        except Exception:
            return 0.0, 0.0

    def get_network_io(self) -> Tuple[float, float]:
        """Get network I/O (sent MB, received MB)."""
        try:
            io = psutil.net_io_counters()
            sent_mb = io.bytes_sent / (1024 * 1024)
            recv_mb = io.bytes_recv / (1024 * 1024)
            return sent_mb, recv_mb
        except Exception:
            return 0.0, 0.0

    def get_thread_count(self) -> int:
        """Get number of threads."""
        try:
            return self.process.num_threads()
        except Exception:
            return 0

    def get_open_files_count(self) -> int:
        """Get number of open files."""
        try:
            return len(self.process.open_files())
        except Exception:
            return 0

    def register_callback(self, callback: Callable):
        """Register a callback for monitoring data."""
        self._callbacks.append(callback)

    def start_monitoring(self, collector: MetricCollector):
        """Start monitoring system resources."""
        if self._monitoring:
            return
        
        self._monitoring = True
        self._monitor_thread = threading.Thread(
            target=self._monitor_loop,
            args=(collector,),
            daemon=True
        )
        self._monitor_thread.start()

    def stop_monitoring(self):
        """Stop monitoring."""
        self._monitoring = False
        if self._monitor_thread:
            self._monitor_thread.join(timeout=5.0)

    def _monitor_loop(self, collector: MetricCollector):
        """Main monitoring loop."""
        while self._monitoring:
            try:
                cpu = self.get_cpu_usage()
                mem_mb, mem_pct = self.get_memory_usage()
                disk_gb, disk_pct = self.get_disk_usage()
                net_sent, net_recv = self.get_network_io()
                threads = self.get_thread_count()
                
                collector.set_gauge("system.cpu.percent", cpu, {"host": "localhost"})
                collector.set_gauge("system.memory.mb", mem_mb, {"host": "localhost"})
                collector.set_gauge("system.memory.percent", mem_pct, {"host": "localhost"})
                collector.set_gauge("system.disk.used_gb", disk_gb, {"host": "localhost"})
                collector.set_gauge("system.disk.percent", disk_pct, {"host": "localhost"})
                collector.set_gauge("system.network.sent_mb", net_sent, {"host": "localhost"})
                collector.set_gauge("system.network.recv_mb", net_recv, {"host": "localhost"})
                collector.set_gauge("system.threads", threads, {"host": "localhost"})
                
                for callback in self._callbacks:
                    try:
                        callback({
                            "cpu": cpu,
                            "memory_mb": mem_mb,
                            "memory_percent": mem_pct,
                            "disk_gb": disk_gb,
                            "disk_percent": disk_pct,
                            "network_sent_mb": net_sent,
                            "network_recv_mb": net_recv,
                            "threads": threads,
                            "timestamp": datetime.now()
                        })
                    except Exception:
                        pass
            except Exception:
                pass
            
            time.sleep(self.interval)


class WorkflowMonitor:
    """Monitors workflow executions and performance."""

    def __init__(self):
        self.active_workflows: Dict[str, Dict[str, Any]] = {}
        self.workflow_history: deque = deque(maxlen=10000)
        self.workflow_stats: Dict[str, Dict[str, Any]] = defaultdict(
            lambda: {
                "total_executions": 0,
                "successful_executions": 0,
                "failed_executions": 0,
                "total_duration_ms": 0.0,
                "avg_duration_ms": 0.0,
                "min_duration_ms": float('inf'),
                "max_duration_ms": 0.0
            }
        )
        self._lock = threading.Lock()

    def start_workflow(self, workflow_id: str, workflow_name: str, metadata: Dict = None):
        """Record the start of a workflow execution."""
        with self._lock:
            self.active_workflows[workflow_id] = {
                "workflow_id": workflow_id,
                "workflow_name": workflow_name,
                "start_time": datetime.now(),
                "metadata": metadata or {},
                "status": "running"
            }

    def complete_workflow(self, workflow_id: str, status: str = "completed", metadata: Dict = None):
        """Record the completion of a workflow execution."""
        with self._lock:
            if workflow_id not in self.active_workflows:
                return
            
            workflow = self.active_workflows[workflow_id]
            end_time = datetime.now()
            duration_ms = (end_time - workflow["start_time"]).total_seconds() * 1000
            
            completed_workflow = {
                **workflow,
                "end_time": end_time,
                "duration_ms": duration_ms,
                "status": status,
                "metadata": {**(workflow.get("metadata", {})), **(metadata or {})}
            }
            
            self.workflow_history.append(completed_workflow)
            del self.active_workflows[workflow_id]
            
            stats = self.workflow_stats[workflow["workflow_name"]]
            stats["total_executions"] += 1
            stats["total_duration_ms"] += duration_ms
            stats["avg_duration_ms"] = stats["total_duration_ms"] / stats["total_executions"]
            stats["min_duration_ms"] = min(stats["min_duration_ms"], duration_ms)
            stats["max_duration_ms"] = max(stats["max_duration_ms"], duration_ms)
            
            if status == "completed":
                stats["successful_executions"] += 1
            else:
                stats["failed_executions"] += 1

    def get_active_workflows(self) -> List[Dict[str, Any]]:
        """Get all currently active workflows."""
        with self._lock:
            return list(self.active_workflows.values())

    def get_workflow_stats(self, workflow_name: str = None) -> Dict[str, Any]:
        """Get statistics for a workflow or all workflows."""
        with self._lock:
            if workflow_name:
                return self.workflow_stats.get(workflow_name, {})
            return dict(self.workflow_stats)

    def get_success_rate(self, workflow_name: str) -> float:
        """Calculate success rate for a workflow."""
        stats = self.workflow_stats.get(workflow_name, {})
        total = stats.get("total_executions", 0)
        if total == 0:
            return 0.0
        successful = stats.get("successful_executions", 0)
        return (successful / total) * 100

    def get_recent_executions(self, limit: int = 100) -> List[Dict[str, Any]]:
        """Get recent workflow executions."""
        with self._lock:
            return list(self.workflow_history)[-limit:]


class MonitoringDashboard:
    """Generates monitoring dashboard data."""

    def __init__(self, collector: MetricCollector, workflow_monitor: WorkflowMonitor,
                 health_checker: HealthChecker):
        self.collector = collector
        self.workflow_monitor = workflow_monitor
        self.health_checker = health_checker

    def generate_dashboard(self, include_history: bool = True) -> Dict[str, Any]:
        """Generate complete dashboard data."""
        health_results = self.health_checker.run_all_checks()
        overall_status = self.health_checker.get_overall_status(health_results)
        
        dashboard = {
            "generated_at": datetime.now().isoformat(),
            "status": overall_status.value,
            "active_workflows": len(self.workflow_monitor.get_active_workflows()),
            "workflow_stats": self.workflow_monitor.get_workflow_stats(),
            "system_metrics": self._get_system_metrics(),
            "active_alerts": len(self.workflow_monitor.get_active_workflows()),
            "health_checks": {
                name: {
                    "status": result.status.value,
                    "message": result.message,
                    "duration_ms": result.duration_ms
                }
                for name, result in health_results.items()
            }
        }
        
        if include_history:
            dashboard["recent_workflows"] = [
                {
                    "workflow_name": w.get("workflow_name"),
                    "status": w.get("status"),
                    "duration_ms": w.get("duration_ms"),
                    "start_time": w.get("start_time").isoformat() if w.get("start_time") else None
                }
                for w in self.workflow_monitor.get_recent_executions(10)
            ]
        
        return dashboard

    def _get_system_metrics(self) -> Dict[str, Any]:
        """Get current system metrics."""
        return {
            "cpu_percent": self.collector.get_current_value("system.cpu.percent") or 0,
            "memory_mb": self.collector.get_current_value("system.memory.mb") or 0,
            "memory_percent": self.collector.get_current_value("system.memory.percent") or 0,
            "disk_percent": self.collector.get_current_value("system.disk.percent") or 0,
            "threads": self.collector.get_current_value("system.threads") or 0
        }

    def export_json(self, output_path: str = None) -> str:
        """Export dashboard data as JSON."""
        dashboard = self.generate_dashboard()
        json_str = json.dumps(dashboard, indent=2, default=str)
        
        if output_path:
            with open(output_path, 'w') as f:
                f.write(json_str)
        
        return json_str


class MonitoringEngine:
    """Main monitoring engine that coordinates all monitoring components."""

    def __init__(self, name: str = "monitoring_engine"):
        self.name = name
        self.status = MonitoringStatus.STOPPED
        
        self.collector = MetricCollector()
        self.alert_manager = AlertManager()
        self.health_checker = HealthChecker()
        self.system_monitor = SystemMonitor(interval=1.0)
        self.workflow_monitor = WorkflowMonitor()
        
        self.dashboard = MonitoringDashboard(
            self.collector,
            self.workflow_monitor,
            self.health_checker
        )
        
        self._monitoring = False
        self._monitor_thread: Optional[threading.Thread] = None
        self._alert_check_thread: Optional[threading.Thread] = None
        self._alert_check_interval = 10.0

    def start(self):
        """Start the monitoring engine."""
        if self._monitoring:
            return
        
        self._monitoring = True
        self.status = MonitoringStatus.HEALTHY
        
        self.system_monitor.start_monitoring(self.collector)
        
        self._monitor_thread = threading.Thread(
            target=self._monitoring_loop,
            daemon=True
        )
        self._monitor_thread.start()
        
        self._alert_check_thread = threading.Thread(
            target=self._alert_check_loop,
            daemon=True
        )
        self._alert_check_thread.start()
        
        logger.info(f"Monitoring engine '{self.name}' started")

    def stop(self):
        """Stop the monitoring engine."""
        if not self._monitoring:
            return
        
        self._monitoring = False
        self.status = MonitoringStatus.STOPPED
        
        self.system_monitor.stop_monitoring()
        
        if self._monitor_thread:
            self._monitor_thread.join(timeout=5.0)
        if self._alert_check_thread:
            self._alert_check_thread.join(timeout=5.0)
        
        logger.info(f"Monitoring engine '{self.name}' stopped")

    def _monitoring_loop(self):
        """Main monitoring loop."""
        while self._monitoring:
            try:
                health_results = self.health_checker.run_all_checks()
                overall = self.health_checker.get_overall_status(health_results)
                
                if overall == MonitoringStatus.CRITICAL:
                    self.status = MonitoringStatus.CRITICAL
                elif overall == MonitoringStatus.WARNING:
                    if self.status != MonitoringStatus.CRITICAL:
                        self.status = MonitoringStatus.WARNING
                else:
                    if self.status != MonitoringStatus.CRITICAL:
                        self.status = MonitoringStatus.HEALTHY
            except Exception:
                pass
            
            time.sleep(5.0)

    def _alert_check_loop(self):
        """Loop that checks alert rules periodically."""
        while self._monitoring:
            try:
                self.alert_manager.check_rules(self.collector)
            except Exception:
                pass
            
            time.sleep(self._alert_check_interval)

    def register_default_health_checks(self):
        """Register default system health checks."""
        def cpu_check() -> HealthCheckResult:
            cpu = self.collector.get_current_value("system.cpu.percent") or 0
            if cpu > 90:
                return HealthCheckResult(
                    name="cpu_usage",
                    status=MonitoringStatus.CRITICAL,
                    message=f"CPU usage critical: {cpu:.1f}%",
                    duration_ms=0,
                    timestamp=datetime.now()
                )
            elif cpu > 70:
                return HealthCheckResult(
                    name="cpu_usage",
                    status=MonitoringStatus.WARNING,
                    message=f"CPU usage high: {cpu:.1f}%",
                    duration_ms=0,
                    timestamp=datetime.now()
                )
            return HealthCheckResult(
                name="cpu_usage",
                status=MonitoringStatus.HEALTHY,
                message=f"CPU usage normal: {cpu:.1f}%",
                duration_ms=0,
                timestamp=datetime.now()
            )

        def memory_check() -> HealthCheckResult:
            mem_pct = self.collector.get_current_value("system.memory.percent") or 0
            if mem_pct > 90:
                return HealthCheckResult(
                    name="memory_usage",
                    status=MonitoringStatus.CRITICAL,
                    message=f"Memory usage critical: {mem_pct:.1f}%",
                    duration_ms=0,
                    timestamp=datetime.now()
                )
            elif mem_pct > 75:
                return HealthCheckResult(
                    name="memory_usage",
                    status=MonitoringStatus.WARNING,
                    message=f"Memory usage high: {mem_pct:.1f}%",
                    duration_ms=0,
                    timestamp=datetime.now()
                )
            return HealthCheckResult(
                name="memory_usage",
                status=MonitoringStatus.HEALTHY,
                message=f"Memory usage normal: {mem_pct:.1f}%",
                duration_ms=0,
                timestamp=datetime.now()
            )

        self.health_checker.register_check("cpu_usage", cpu_check)
        self.health_checker.register_check("memory_usage", memory_check)

    def register_default_alert_rules(self):
        """Register default alert rules."""
        self.alert_manager.register_rule(AlertRule(
            name="high_cpu",
            metric_name="system.cpu.percent",
            threshold=90.0,
            condition="greater",
            severity=MonitoringStatus.CRITICAL,
            cooldown_seconds=300
        ))
        
        self.alert_manager.register_rule(AlertRule(
            name="high_memory",
            metric_name="system.memory.percent",
            threshold=85.0,
            condition="greater",
            severity=MonitoringStatus.WARNING,
            cooldown_seconds=300
        ))


if __name__ == '__main__':
    print("Workflow Monitoring Module - Example Usage")
    
    engine = MonitoringEngine("example_monitor")
    engine.register_default_health_checks()
    engine.register_default_alert_rules()
    
    engine.start()
    print(f"Monitoring engine status: {engine.status.value}")
    
    time.sleep(5)
    
    dashboard = engine.dashboard.generate_dashboard()
    print(f"Dashboard data: {json.dumps(dashboard, indent=2, default=str)}")
    
    engine.stop()
    print("Monitoring engine stopped")
